import type { UIConfig } from "../types.ts";

export const bottomDockConfig: UIConfig["bottomDock"] = {
    panel: {
        fill: 0xe8e4da,
        border: 0x6c665d,
        borderWidth: 2,
        radius: 12,
        glossFill: 0xffffff,
        glossAlpha: 0.05,
        headerFill: 0xf3f2ed,
        headerBorder: 0x7a746b,
        titleText: 0x37332e,
        bodyText: 0x46423d,
        inset: 3,
        fontFamily: "Noto Sans",
        titleFontSize: 15,
        bodyFontSize: 13,
        captionFontSize: 10,
    },
    shell: {
        fill: 0xd5d0c4,
        border: 0x6f6a61,
        borderWidth: 2,
        radius: 12,
        glossFill: 0xffffff,
        glossAlpha: 0.04,
    },
    slot: {
        fill: 0x9db9cb,
        border: 0x587186,
        borderWidth: 2,
        radius: 10,
        glossFill: 0xffffff,
        glossAlpha: 0.08,
        activeFill: 0x69b84c,
        activeBorder: 0x0d5f2d,
    },
    rail: {
        fill: 0xcdc7bc,
        radius: 10,
        dividerFill: 0x918b81,
    },
    chip: {
        fill: 0x2b61a4,
        border: 0xffffff,
        text: 0xffffff,
        radius: 4,
    },
    timer: {
        fill: 0xefede7,
        border: 0x6a6a66,
        stripFill: 0xd8d4c9,
        text: 0x2f2e2c,
        subtext: 0x55524c,
    },
};
