import type { UIConfig } from "../types.ts";

export const tradeConfig: UIConfig["trade"] = {
    editor: {
        offerWidth: 430,
        windowHeight: 84,
        cardWidth: 52,
        leftX: 20,
        panelGap: 20,
        rowGap: 4,
        bottomOffset: 20,
        askExtraOffset: 110,
        compactAskBaseWidth: 430,
        ckAskBaseWidth: 430,
        ckPossibleAskWidth: 430,
        basePossibleAskWidth: 430,
        contentInsetLeft: 70,
        railWidth: 56,
        railRadius: 14,
        iconSize: 28,
        surfaceFill: 0xf2f0ea,
        surfaceBorder: 0x0f79c8,
        surfaceBorderWidth: 2,
        railFill: 0xb9e8fb,
        actionRailGap: 8,
        actionRailWidth: 60,
    },
    offers: {
        laneRightOffset: 430,
        laneTop: 20,
        laneGap: 70,
        scale: 0.8,
        cardWindowWidth: 250,
        cardWindowHeight: 80,
        cardWidth: 40,
        panelGap: 30,
        markerPlusX: 263,
        markerPlusY: -8,
        markerMinusX: 260,
        markerMinusY: -20,
        acceptAvatarStep: 50,
        acceptPanelPadding: 10,
        acceptPanelHeight: 80,
        counterButtonWindowSize: 42,
        offererPanelWidth: 60,
        offererPanelHeight: 80,
        offererOffsetX: -70,
        enterAnimationOffsetX: 40,
    },
};
